# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5928216d14c645d64f167fe5c0018e3c46268889c328b96dd605196438d76bd559007c48ee24622e9b27449f46b512671e646981037b7b51d92b871efc8b827c

test:
  secret_key_base: 34ecd5c6bca5c0d26681cd3a220bab37e4d5524e713db6287bcbba5fa123cc2c1d2c0c6059beebbbd96694b60d943961b0c9f234cca825ab6545471cae5999bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
